### ISSUE TITLE
Performance regression of ~5% CPU for 0.5.1 vs 0.4.0

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/browserid-verifier#80] opened 2016-02-25 22:15 UTC
This is htop output from two servers in the tokenserver cluster. The top panel is running 0.4.0 and the bottom panel is running 0.5.1. I filtered only the `worker.js` processes and after watching it for a little while, 0.5.1 consistently uses ~5% more CPU.

![screen shot 2016-02-25 at 2 06 44 pm](https://cloud.githubusercontent.com/assets/83972/13336185/a4589888-dbc9-11e5-9327-e9dde70dcd82.png)

Here's the canary server compared to a couple others in the cluster. 

![screen shot 2016-02-25 at 2 10 22 pm](https://cloud.githubusercontent.com/assets/83972/13336183/9fbb2e30-dbc9-11e5-9d9e-b7064f6d8653.png)

**Comment by rfk** [comment] 2016-02-26 02:34
The only changes of significant with the new version could be:

* updated dependencies that got sucked when making the new version
* the change to use builtin `url` module rather than custom `urlparse` module for various validation steps

I supposed it's not *entirely* implausible that the switch in URL parsing could have a performance penalty at scale.  @mostlygeek how important is it to you that we try to get this number back down?

**Comment by rfk** [comment] 2016-02-26 03:38
Hmm, looks like builtin `url.parse` is indeed significantly slower than the previous `urlparse` module, here's the timing for parsing a URL 100000 times:

```
$> node testit.js 
urlparse took 231 millis
url.parse took 1071 millis
$> node testit.js 
urlparse took 262 millis
url.parse took 1253 millis
$>
```

**Comment by mostlygeek** [comment] 2016-02-26 03:44
It's not that important. I don't think it's not worth spending much time on it. The latency for responses hasn't changed and auto-scaling will handle required number of servers. It might cost us a few extra pennies a day tough ;)

**Comment by jrgm** [comment] 2016-02-26 03:57
I can't reproduce your results @rfk but don't know what your testit.js looked like (or the url). 

Just curious, but is this running in prod on node 4, or node 0.10?

**Comment by rfk** [comment] 2016-02-26 04:01
```
$> cat testit.js 

var urlparse = require('urlparse');
var url = require('url');

function timeit(name, func) {
  var t1 = +Date.now();
  x = 100000;
  while (x > 0) {
    func("http://localhost:1234")
    x -= 1;
  }
  console.log(name + " took " + (+Date.now() - t1) + " millis");
}

timeit("urlparse module", urlparse);
timeit("builtin url.parse", url.parse);
$>
$> node testit.js 
urlparse module took 233 millis
builtin url.parse took 1122 millis
$>
$> node --version
v0.10.42
```

Could certainly be my old version of nodejs playing a part.

**Comment by jrgm** [comment] 2016-02-26 04:14
Nevermind. PEBKAC. But it is faster, either parser, in 4.x.

**Comment by mostlygeek** [comment] 2016-02-26 20:27
Not sure about the motivation to use `url.parse` over `urlparse` but I'm willing to accept the slow down for a well maintained and safer library. @rfk feel free to close this issue if you think it is appropriate.

**Comment by rfk** [comment] 2016-02-28 22:42
> Not sure about the motivation to use url.parse over urlparse

FTR: `urlparse` is unmaintained so moving to something builtin to node seemed like a good tradeoff.

**Comment by shane-tomlinson** [comment] 2016-02-29 17:49
@rfk, @mostlygeek - can you triage this as you see appropriate?

**Comment by rfk** [comment] 2016-02-29 20:25
We decided we're happy to eat this perf change

**Closed by rfk** 2016-02-29 20:25 UTC
